features: [NPHI, RHOB]
contamination: 0.1
random_state: 42
imputer_strategy: median
scaler: standard # one of: standard | minmax | robust
model_path: models/iforest_pipeline.joblib
meta_path: models/iforest_meta.json